### ISSUE TITLE
Certificate verify issue on deskop

### ISSUE THREAD

**Issue by snylonue** [ProjectAnni/annix#16]
Example: https://annil_serverless.shuttleapp.rs

```
DioError [unknown]; null
Error: HandshakeException: Handshake error in client (OS Error:
CERTIFICATE_VERIFY_FAILED: Hostname mismatch(../../third_party/boringssl/src/ss|/handshake.cc:393))
```

When testing on ios, such issue does not occur.

**Comment by Yesterday17** [comment]
Desktop means Windows Platform?

**Comment by SeraphJACK** [comment]
Can reproduce on Linux.

**Comment by snylonue** [comment]
> Desktop means Windows Platform?

Yes.

**Comment by Yesterday17** [comment]
Planning to migrate all http-related code to native. :thinking:

**Comment by Yesterday17** [comment]
According to the source code, the `skipCertificateVerification` option is never used. I plan to reintroduce it this weekend as a temporary fix.
